=== Siddharth2207/zeroex-take-order-bot/schema/orders.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/Order",
    "definitions": {
        "Order": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "owner": {
                        "type": "string",
                        "title": "Order Owner",
                        "pattern": "^0x[0-9a-zA-Z]{40}$"
                    },
                    "handleIO": {
                        "type": "boolean",
                        "title": "Order Handle IO"
                    },
                    "evaluable": {
                        "type": "object",
                        "properties": {
                            "interpreter": {
                                "type": "string",
                                "title": "Interpreter Address",
                                "pattern": "^0x[0-9a-zA-Z]{40}$"
                            },
                            "store": {
                                "type": "string",
                                "title": "Store Address",
                                "pattern": "^0x[0-9a-zA-Z]{40}$"
                            },
                            "expression": {
                                "type": "string",
                                "title": "Expression Address",
                                "pattern": "^0x[0-9a-zA-Z]{40}$"
                            }
                        },
                        "required": [
                            "interpreter",
                            "store",
                            "expression"
                        ],
                        "additionalProperties": false,
                        "title": "Order Evaluable Struct",
                        "description": "The evaluable struct of the Order"
                    },
                    "validInputs": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "token": {
                                    "type": "string",
                                    "title": "Token Address",
                                    "pattern": "^0x[0-9a-zA-Z]{40}$"
                                },
                                "decimals": {
                                    "type": "number",
                                    "title": "Token Decimals"
                                },
                                "vaultId": {
                                    "type": "string",
                                    "title": "Vault ID",
                                    "pattern": "^0x[0-9a-zA-Z]{64}$"
                                }
                            },
                            "required": [
                                "token",
                                "decimals",
                                "vaultId"
                            ],
                            "additionalProperties": false
                        },
                        "title": "Order Valid Inputs"
                    },
                    "validOutputs": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "token": {
                                    "type": "string",
                                    "title": "Token Address",
                                    "pattern": "^0x[0-9a-zA-Z]{40}$"
                                },
                                "decimals": {
                                    "type": "number",
                                    "title": "Token Decimals"
                                },
                                "vaultId": {
                                    "type": "string",
                                    "title": "Vault ID",
                                    "pattern": "^0x[0-9a-zA-Z]{64}$"
                                }
                            },
                            "required": [
                                "token",
                                "decimals",
                                "vaultId"
                            ],
                            "additionalProperties": false
                        },
                        "title": "Order Valid Outputs"
                    }
                },
                "required": [
                    "owner",
                    "handleIO",
                    "evaluable",
                    "validInputs",
                    "validOutputs"
                ],
                "additionalProperties": false
            }
        }
    }
}

=== Siddharth2207/zeroex-take-order-bot/example.orders.json
[
    {
        "owner": "0xA25f22b0Ab021A9cA1513C892e6FaacC50e92907",
        "handleIO": true,
        "evaluable": {
            "interpreter": "0x8ECd48e70954Dec0f45e4551f039A0D24038c536",
            "store": "0x13cdD62F032125Fea331Cf8B79eADE8830CD5dab",
            "expression": "0xF77F4C334F3De948BaEdf814Af7f82365171e559"
        },
        "validInputs": [{
            "token": "0xc2132D05D31c914a87C6611C10748AEb04B58e8F",
            "decimals": 6,
            "vaultId": "0x84e4bec2eccb5e3f00d2db11f82a85c0329fa210edb34fbc266e8d2e9d10ee28"
        }],
        "validOutputs": [{
            "token": "0x84342e932797FC62814189f01F0Fb05F52519708",
            "decimals": 18,
            "vaultId": "0x84e4bec2eccb5e3f00d2db11f82a85c0329fa210edb34fbc266e8d2e9d10ee28"
        }]
    }
]

=== Siddharth2207/zeroex-take-order-bot/orders.json
[
    {
      "owner": "0x53AB61eE41FA202227Eb4e7B176208FC626DC8A9",
      "handleIO": true,
      "evaluable": {
        "interpreter": "0xE82Ec43bd3E516878C6dF2088E769A02c04984A7",
        "store": "0xEFCA12B267787Ab70961D8150B6BdC2Ed14e9Ed3",
        "expression": "0x4A050e7799eed2f6073eBA02d10C511A39a9bd21"
      },
      "validInputs": [
        {
          "token": "0xc2132D05D31c914a87C6611C10748AEb04B58e8F",
          "decimals": 6,
          "vaultId": "0x406c72a303ccd9d5c3c46876722209ce70dddcc2d70757593c71b57f83f0d442"
        }
      ],
      "validOutputs": [
        {
          "token": "0x84342e932797FC62814189f01F0Fb05F52519708",
          "decimals": 18,
          "vaultId": "0x406c72a303ccd9d5c3c46876722209ce70dddcc2d70757593c71b57f83f0d442"
        }
      ]
    }
  ]
